// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_wrapper.proto

package com.zh.model;

public interface DataWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .DataWrapper.DataType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .DataWrapper.DataType type = 1;</code>
   */
  DataWrapper.DataType getType();

  /**
   * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
   */
  RegisterRequestDTO getRegisterRequestDTO();
  /**
   * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
   */
  RegisterRequestDTOOrBuilder getRegisterRequestDTOOrBuilder();

  /**
   * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
   */
  RegisterResponseDTO getRegisterResponseDTO();
  /**
   * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
   */
  RegisterResponseDTOOrBuilder getRegisterResponseDTOOrBuilder();

  /**
   * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
   */
  LoginRequestDTO getLoginRequestDTO();
  /**
   * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
   */
  LoginRequestDTOOrBuilder getLoginRequestDTOOrBuilder();

  /**
   * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
   */
  LoginResponseDTO getLoginResponseDTO();
  /**
   * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
   */
  LoginResponseDTOOrBuilder getLoginResponseDTOOrBuilder();

  public DataWrapper.DataCase getDataCase();
}
