// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_wrapper.proto

package com.zh.model;

/**
 * Protobuf type {@code DataWrapper}
 */
public  final class DataWrapper extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DataWrapper)
        DataWrapperOrBuilder {
  // Use DataWrapper.newBuilder() to construct.
  private DataWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataWrapper() {
    type_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DataWrapper(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            RegisterRequestDTO.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((RegisterRequestDTO) data_).toBuilder();
            }
            data_ =
                input.readMessage(RegisterRequestDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((RegisterRequestDTO) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 26: {
            RegisterResponseDTO.Builder subBuilder = null;
            if (dataCase_ == 3) {
              subBuilder = ((RegisterResponseDTO) data_).toBuilder();
            }
            data_ =
                input.readMessage(RegisterResponseDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((RegisterResponseDTO) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 3;
            break;
          }
          case 34: {
            LoginRequestDTO.Builder subBuilder = null;
            if (dataCase_ == 4) {
              subBuilder = ((LoginRequestDTO) data_).toBuilder();
            }
            data_ =
                input.readMessage(LoginRequestDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((LoginRequestDTO) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 4;
            break;
          }
          case 42: {
            LoginResponseDTO.Builder subBuilder = null;
            if (dataCase_ == 5) {
              subBuilder = ((LoginResponseDTO) data_).toBuilder();
            }
            data_ =
                input.readMessage(LoginResponseDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((LoginResponseDTO) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 5;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DataWrapperModel.internal_static_DataWrapper_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DataWrapperModel.internal_static_DataWrapper_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DataWrapper.class, DataWrapper.Builder.class);
  }

  /**
   * Protobuf enum {@code DataWrapper.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>register_request = 0;</code>
     */
    register_request(0),
    /**
     * <code>register_response = 1;</code>
     */
    register_response(1),
    /**
     * <code>login_request = 2;</code>
     */
    login_request(2),
    /**
     * <code>login_response = 3;</code>
     */
    login_response(3),
    /**
     * <code>friend_add_request = 4;</code>
     */
    friend_add_request(4),
    /**
     * <code>friend_add_response = 5;</code>
     */
    friend_add_response(5),
    /**
     * <code>message_send_request = 6;</code>
     */
    message_send_request(6),
    /**
     * <code>message_send_response = 7;</code>
     */
    message_send_response(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>register_request = 0;</code>
     */
    public static final int register_request_VALUE = 0;
    /**
     * <code>register_response = 1;</code>
     */
    public static final int register_response_VALUE = 1;
    /**
     * <code>login_request = 2;</code>
     */
    public static final int login_request_VALUE = 2;
    /**
     * <code>login_response = 3;</code>
     */
    public static final int login_response_VALUE = 3;
    /**
     * <code>friend_add_request = 4;</code>
     */
    public static final int friend_add_request_VALUE = 4;
    /**
     * <code>friend_add_response = 5;</code>
     */
    public static final int friend_add_response_VALUE = 5;
    /**
     * <code>message_send_request = 6;</code>
     */
    public static final int message_send_request_VALUE = 6;
    /**
     * <code>message_send_response = 7;</code>
     */
    public static final int message_send_response_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return register_request;
        case 1: return register_response;
        case 2: return login_request;
        case 3: return login_response;
        case 4: return friend_add_request;
        case 5: return friend_add_response;
        case 6: return message_send_request;
        case 7: return message_send_response;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DataWrapper.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DataWrapper.DataType)
  }

  private int dataCase_ = 0;
  private Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite {
    REGISTERREQUESTDTO(2),
    REGISTERRESPONSEDTO(3),
    LOGINREQUESTDTO(4),
    LOGINRESPONSEDTO(5),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return REGISTERREQUESTDTO;
        case 3: return REGISTERRESPONSEDTO;
        case 4: return LOGINREQUESTDTO;
        case 5: return LOGINRESPONSEDTO;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional .DataWrapper.DataType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .DataWrapper.DataType type = 1;</code>
   */
  public DataWrapper.DataType getType() {
    DataWrapper.DataType result = DataWrapper.DataType.valueOf(type_);
    return result == null ? DataWrapper.DataType.UNRECOGNIZED : result;
  }

  public static final int REGISTERREQUESTDTO_FIELD_NUMBER = 2;
  /**
   * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
   */
  public RegisterRequestDTO getRegisterRequestDTO() {
    if (dataCase_ == 2) {
       return (RegisterRequestDTO) data_;
    }
    return RegisterRequestDTO.getDefaultInstance();
  }
  /**
   * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
   */
  public RegisterRequestDTOOrBuilder getRegisterRequestDTOOrBuilder() {
    if (dataCase_ == 2) {
       return (RegisterRequestDTO) data_;
    }
    return RegisterRequestDTO.getDefaultInstance();
  }

  public static final int REGISTERRESPONSEDTO_FIELD_NUMBER = 3;
  /**
   * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
   */
  public RegisterResponseDTO getRegisterResponseDTO() {
    if (dataCase_ == 3) {
       return (RegisterResponseDTO) data_;
    }
    return RegisterResponseDTO.getDefaultInstance();
  }
  /**
   * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
   */
  public RegisterResponseDTOOrBuilder getRegisterResponseDTOOrBuilder() {
    if (dataCase_ == 3) {
       return (RegisterResponseDTO) data_;
    }
    return RegisterResponseDTO.getDefaultInstance();
  }

  public static final int LOGINREQUESTDTO_FIELD_NUMBER = 4;
  /**
   * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
   */
  public LoginRequestDTO getLoginRequestDTO() {
    if (dataCase_ == 4) {
       return (LoginRequestDTO) data_;
    }
    return LoginRequestDTO.getDefaultInstance();
  }
  /**
   * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
   */
  public LoginRequestDTOOrBuilder getLoginRequestDTOOrBuilder() {
    if (dataCase_ == 4) {
       return (LoginRequestDTO) data_;
    }
    return LoginRequestDTO.getDefaultInstance();
  }

  public static final int LOGINRESPONSEDTO_FIELD_NUMBER = 5;
  /**
   * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
   */
  public LoginResponseDTO getLoginResponseDTO() {
    if (dataCase_ == 5) {
       return (LoginResponseDTO) data_;
    }
    return LoginResponseDTO.getDefaultInstance();
  }
  /**
   * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
   */
  public LoginResponseDTOOrBuilder getLoginResponseDTOOrBuilder() {
    if (dataCase_ == 5) {
       return (LoginResponseDTO) data_;
    }
    return LoginResponseDTO.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != DataWrapper.DataType.register_request.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (RegisterRequestDTO) data_);
    }
    if (dataCase_ == 3) {
      output.writeMessage(3, (RegisterResponseDTO) data_);
    }
    if (dataCase_ == 4) {
      output.writeMessage(4, (LoginRequestDTO) data_);
    }
    if (dataCase_ == 5) {
      output.writeMessage(5, (LoginResponseDTO) data_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != DataWrapper.DataType.register_request.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (RegisterRequestDTO) data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (RegisterResponseDTO) data_);
    }
    if (dataCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (LoginRequestDTO) data_);
    }
    if (dataCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (LoginResponseDTO) data_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DataWrapper)) {
      return super.equals(obj);
    }
    DataWrapper other = (DataWrapper) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && getDataCase().equals(
        other.getDataCase());
    if (!result) return false;
    switch (dataCase_) {
      case 2:
        result = result && getRegisterRequestDTO()
            .equals(other.getRegisterRequestDTO());
        break;
      case 3:
        result = result && getRegisterResponseDTO()
            .equals(other.getRegisterResponseDTO());
        break;
      case 4:
        result = result && getLoginRequestDTO()
            .equals(other.getLoginRequestDTO());
        break;
      case 5:
        result = result && getLoginResponseDTO()
            .equals(other.getLoginResponseDTO());
        break;
      case 0:
      default:
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + REGISTERREQUESTDTO_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterRequestDTO().hashCode();
        break;
      case 3:
        hash = (37 * hash) + REGISTERRESPONSEDTO_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterResponseDTO().hashCode();
        break;
      case 4:
        hash = (37 * hash) + LOGINREQUESTDTO_FIELD_NUMBER;
        hash = (53 * hash) + getLoginRequestDTO().hashCode();
        break;
      case 5:
        hash = (37 * hash) + LOGINRESPONSEDTO_FIELD_NUMBER;
        hash = (53 * hash) + getLoginResponseDTO().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DataWrapper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DataWrapper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DataWrapper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DataWrapper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DataWrapper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DataWrapper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DataWrapper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DataWrapper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DataWrapper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DataWrapper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DataWrapper prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DataWrapper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DataWrapper)
          DataWrapperOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataWrapperModel.internal_static_DataWrapper_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataWrapperModel.internal_static_DataWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataWrapper.class, DataWrapper.Builder.class);
    }

    // Construct using com.zh.model.DataWrapper.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      dataCase_ = 0;
      data_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DataWrapperModel.internal_static_DataWrapper_descriptor;
    }

    public DataWrapper getDefaultInstanceForType() {
      return DataWrapper.getDefaultInstance();
    }

    public DataWrapper build() {
      DataWrapper result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public DataWrapper buildPartial() {
      DataWrapper result = new DataWrapper(this);
      result.type_ = type_;
      if (dataCase_ == 2) {
        if (registerRequestDTOBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = registerRequestDTOBuilder_.build();
        }
      }
      if (dataCase_ == 3) {
        if (registerResponseDTOBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = registerResponseDTOBuilder_.build();
        }
      }
      if (dataCase_ == 4) {
        if (loginRequestDTOBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = loginRequestDTOBuilder_.build();
        }
      }
      if (dataCase_ == 5) {
        if (loginResponseDTOBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = loginResponseDTOBuilder_.build();
        }
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DataWrapper) {
        return mergeFrom((DataWrapper)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DataWrapper other) {
      if (other == DataWrapper.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getDataCase()) {
        case REGISTERREQUESTDTO: {
          mergeRegisterRequestDTO(other.getRegisterRequestDTO());
          break;
        }
        case REGISTERRESPONSEDTO: {
          mergeRegisterResponseDTO(other.getRegisterResponseDTO());
          break;
        }
        case LOGINREQUESTDTO: {
          mergeLoginRequestDTO(other.getLoginRequestDTO());
          break;
        }
        case LOGINRESPONSEDTO: {
          mergeLoginResponseDTO(other.getLoginResponseDTO());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DataWrapper parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DataWrapper) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>optional .DataWrapper.DataType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .DataWrapper.DataType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .DataWrapper.DataType type = 1;</code>
     */
    public DataWrapper.DataType getType() {
      DataWrapper.DataType result = DataWrapper.DataType.valueOf(type_);
      return result == null ? DataWrapper.DataType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .DataWrapper.DataType type = 1;</code>
     */
    public Builder setType(DataWrapper.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .DataWrapper.DataType type = 1;</code>
     */
    public Builder clearType() {

      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            RegisterRequestDTO, RegisterRequestDTO.Builder, RegisterRequestDTOOrBuilder> registerRequestDTOBuilder_;
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    public RegisterRequestDTO getRegisterRequestDTO() {
      if (registerRequestDTOBuilder_ == null) {
        if (dataCase_ == 2) {
          return (RegisterRequestDTO) data_;
        }
        return RegisterRequestDTO.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return registerRequestDTOBuilder_.getMessage();
        }
        return RegisterRequestDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    public Builder setRegisterRequestDTO(RegisterRequestDTO value) {
      if (registerRequestDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        registerRequestDTOBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    public Builder setRegisterRequestDTO(
        RegisterRequestDTO.Builder builderForValue) {
      if (registerRequestDTOBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        registerRequestDTOBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    public Builder mergeRegisterRequestDTO(RegisterRequestDTO value) {
      if (registerRequestDTOBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != RegisterRequestDTO.getDefaultInstance()) {
          data_ = RegisterRequestDTO.newBuilder((RegisterRequestDTO) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          registerRequestDTOBuilder_.mergeFrom(value);
        }
        registerRequestDTOBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    public Builder clearRegisterRequestDTO() {
      if (registerRequestDTOBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        registerRequestDTOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    public RegisterRequestDTO.Builder getRegisterRequestDTOBuilder() {
      return getRegisterRequestDTOFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    public RegisterRequestDTOOrBuilder getRegisterRequestDTOOrBuilder() {
      if ((dataCase_ == 2) && (registerRequestDTOBuilder_ != null)) {
        return registerRequestDTOBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (RegisterRequestDTO) data_;
        }
        return RegisterRequestDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RegisterRequestDTO registerRequestDTO = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            RegisterRequestDTO, RegisterRequestDTO.Builder, RegisterRequestDTOOrBuilder>
        getRegisterRequestDTOFieldBuilder() {
      if (registerRequestDTOBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = RegisterRequestDTO.getDefaultInstance();
        }
        registerRequestDTOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                RegisterRequestDTO, RegisterRequestDTO.Builder, RegisterRequestDTOOrBuilder>(
                (RegisterRequestDTO) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();;
      return registerRequestDTOBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            RegisterResponseDTO, RegisterResponseDTO.Builder, RegisterResponseDTOOrBuilder> registerResponseDTOBuilder_;
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    public RegisterResponseDTO getRegisterResponseDTO() {
      if (registerResponseDTOBuilder_ == null) {
        if (dataCase_ == 3) {
          return (RegisterResponseDTO) data_;
        }
        return RegisterResponseDTO.getDefaultInstance();
      } else {
        if (dataCase_ == 3) {
          return registerResponseDTOBuilder_.getMessage();
        }
        return RegisterResponseDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    public Builder setRegisterResponseDTO(RegisterResponseDTO value) {
      if (registerResponseDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        registerResponseDTOBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    public Builder setRegisterResponseDTO(
        RegisterResponseDTO.Builder builderForValue) {
      if (registerResponseDTOBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        registerResponseDTOBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    public Builder mergeRegisterResponseDTO(RegisterResponseDTO value) {
      if (registerResponseDTOBuilder_ == null) {
        if (dataCase_ == 3 &&
            data_ != RegisterResponseDTO.getDefaultInstance()) {
          data_ = RegisterResponseDTO.newBuilder((RegisterResponseDTO) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 3) {
          registerResponseDTOBuilder_.mergeFrom(value);
        }
        registerResponseDTOBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    public Builder clearRegisterResponseDTO() {
      if (registerResponseDTOBuilder_ == null) {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
        }
        registerResponseDTOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    public RegisterResponseDTO.Builder getRegisterResponseDTOBuilder() {
      return getRegisterResponseDTOFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    public RegisterResponseDTOOrBuilder getRegisterResponseDTOOrBuilder() {
      if ((dataCase_ == 3) && (registerResponseDTOBuilder_ != null)) {
        return registerResponseDTOBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 3) {
          return (RegisterResponseDTO) data_;
        }
        return RegisterResponseDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .RegisterResponseDTO registerResponseDTO = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            RegisterResponseDTO, RegisterResponseDTO.Builder, RegisterResponseDTOOrBuilder>
        getRegisterResponseDTOFieldBuilder() {
      if (registerResponseDTOBuilder_ == null) {
        if (!(dataCase_ == 3)) {
          data_ = RegisterResponseDTO.getDefaultInstance();
        }
        registerResponseDTOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                RegisterResponseDTO, RegisterResponseDTO.Builder, RegisterResponseDTOOrBuilder>(
                (RegisterResponseDTO) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 3;
      onChanged();;
      return registerResponseDTOBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            LoginRequestDTO, LoginRequestDTO.Builder, LoginRequestDTOOrBuilder> loginRequestDTOBuilder_;
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    public LoginRequestDTO getLoginRequestDTO() {
      if (loginRequestDTOBuilder_ == null) {
        if (dataCase_ == 4) {
          return (LoginRequestDTO) data_;
        }
        return LoginRequestDTO.getDefaultInstance();
      } else {
        if (dataCase_ == 4) {
          return loginRequestDTOBuilder_.getMessage();
        }
        return LoginRequestDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    public Builder setLoginRequestDTO(LoginRequestDTO value) {
      if (loginRequestDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        loginRequestDTOBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    public Builder setLoginRequestDTO(
        LoginRequestDTO.Builder builderForValue) {
      if (loginRequestDTOBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        loginRequestDTOBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    public Builder mergeLoginRequestDTO(LoginRequestDTO value) {
      if (loginRequestDTOBuilder_ == null) {
        if (dataCase_ == 4 &&
            data_ != LoginRequestDTO.getDefaultInstance()) {
          data_ = LoginRequestDTO.newBuilder((LoginRequestDTO) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 4) {
          loginRequestDTOBuilder_.mergeFrom(value);
        }
        loginRequestDTOBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    public Builder clearLoginRequestDTO() {
      if (loginRequestDTOBuilder_ == null) {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
        }
        loginRequestDTOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    public LoginRequestDTO.Builder getLoginRequestDTOBuilder() {
      return getLoginRequestDTOFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    public LoginRequestDTOOrBuilder getLoginRequestDTOOrBuilder() {
      if ((dataCase_ == 4) && (loginRequestDTOBuilder_ != null)) {
        return loginRequestDTOBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 4) {
          return (LoginRequestDTO) data_;
        }
        return LoginRequestDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .LoginRequestDTO loginRequestDTO = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            LoginRequestDTO, LoginRequestDTO.Builder, LoginRequestDTOOrBuilder>
        getLoginRequestDTOFieldBuilder() {
      if (loginRequestDTOBuilder_ == null) {
        if (!(dataCase_ == 4)) {
          data_ = LoginRequestDTO.getDefaultInstance();
        }
        loginRequestDTOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                LoginRequestDTO, LoginRequestDTO.Builder, LoginRequestDTOOrBuilder>(
                (LoginRequestDTO) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 4;
      onChanged();;
      return loginRequestDTOBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
            LoginResponseDTO, LoginResponseDTO.Builder, LoginResponseDTOOrBuilder> loginResponseDTOBuilder_;
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    public LoginResponseDTO getLoginResponseDTO() {
      if (loginResponseDTOBuilder_ == null) {
        if (dataCase_ == 5) {
          return (LoginResponseDTO) data_;
        }
        return LoginResponseDTO.getDefaultInstance();
      } else {
        if (dataCase_ == 5) {
          return loginResponseDTOBuilder_.getMessage();
        }
        return LoginResponseDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    public Builder setLoginResponseDTO(LoginResponseDTO value) {
      if (loginResponseDTOBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        loginResponseDTOBuilder_.setMessage(value);
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    public Builder setLoginResponseDTO(
        LoginResponseDTO.Builder builderForValue) {
      if (loginResponseDTOBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        loginResponseDTOBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    public Builder mergeLoginResponseDTO(LoginResponseDTO value) {
      if (loginResponseDTOBuilder_ == null) {
        if (dataCase_ == 5 &&
            data_ != LoginResponseDTO.getDefaultInstance()) {
          data_ = LoginResponseDTO.newBuilder((LoginResponseDTO) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 5) {
          loginResponseDTOBuilder_.mergeFrom(value);
        }
        loginResponseDTOBuilder_.setMessage(value);
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    public Builder clearLoginResponseDTO() {
      if (loginResponseDTOBuilder_ == null) {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
        }
        loginResponseDTOBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    public LoginResponseDTO.Builder getLoginResponseDTOBuilder() {
      return getLoginResponseDTOFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    public LoginResponseDTOOrBuilder getLoginResponseDTOOrBuilder() {
      if ((dataCase_ == 5) && (loginResponseDTOBuilder_ != null)) {
        return loginResponseDTOBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 5) {
          return (LoginResponseDTO) data_;
        }
        return LoginResponseDTO.getDefaultInstance();
      }
    }
    /**
     * <code>optional .LoginResponseDTO loginResponseDTO = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            LoginResponseDTO, LoginResponseDTO.Builder, LoginResponseDTOOrBuilder>
        getLoginResponseDTOFieldBuilder() {
      if (loginResponseDTOBuilder_ == null) {
        if (!(dataCase_ == 5)) {
          data_ = LoginResponseDTO.getDefaultInstance();
        }
        loginResponseDTOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                LoginResponseDTO, LoginResponseDTO.Builder, LoginResponseDTOOrBuilder>(
                (LoginResponseDTO) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 5;
      onChanged();;
      return loginResponseDTOBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:DataWrapper)
  }

  // @@protoc_insertion_point(class_scope:DataWrapper)
  private static final DataWrapper DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DataWrapper();
  }

  public static DataWrapper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataWrapper>
      PARSER = new com.google.protobuf.AbstractParser<DataWrapper>() {
    public DataWrapper parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataWrapper(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataWrapper> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DataWrapper> getParserForType() {
    return PARSER;
  }

  public DataWrapper getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

