// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_response.proto

package com.zh.model;

public interface LoginResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .UserDTO user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>optional .UserDTO user = 1;</code>
   */
  UserDTO getUser();
  /**
   * <code>optional .UserDTO user = 1;</code>
   */
  UserDTOOrBuilder getUserOrBuilder();

  /**
   * <code>repeated .UserDTO friends = 2;</code>
   */
  java.util.List<UserDTO>
      getFriendsList();
  /**
   * <code>repeated .UserDTO friends = 2;</code>
   */
  UserDTO getFriends(int index);
  /**
   * <code>repeated .UserDTO friends = 2;</code>
   */
  int getFriendsCount();
  /**
   * <code>repeated .UserDTO friends = 2;</code>
   */
  java.util.List<? extends UserDTOOrBuilder>
      getFriendsOrBuilderList();
  /**
   * <code>repeated .UserDTO friends = 2;</code>
   */
  UserDTOOrBuilder getFriendsOrBuilder(
          int index);
}
