// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_response.proto

package com.zh.model;

public final class LoginResponseDTOModel {
  private LoginResponseDTOModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponseDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024login_response.proto\032\nuser.proto\"E\n\020Lo" +
      "ginResponseDTO\022\026\n\004user\030\001 \001(\0132\010.UserDTO\022\031" +
      "\n\007friends\030\002 \003(\0132\010.UserDTOB\'\n\014com.zh.mode" +
      "lB\025LoginResponseDTOModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          UserDTOModel.getDescriptor(),
        }, assigner);
    internal_static_LoginResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponseDTO_descriptor,
        new String[] { "User", "Friends", });
    UserDTOModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
