// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.zh.model;

public interface LoginRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string code = 1;</code>
   */
  String getCode();
  /**
   * <code>optional string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>optional string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
