// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register_response.proto

package com.zh.model;

public interface RegisterResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>optional string msg = 2;</code>
   */
  String getMsg();
  /**
   * <code>optional string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
