// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zh.model;

public final class UserDTOModel {
  private UserDTOModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nuser.proto\"\225\001\n\007UserDTO\022\n\n\002id\030\001 \001(\t\022\014\n\004" +
      "code\030\002 \001(\t\022\020\n\010nickName\030\003 \001(\t\022\031\n\003sex\030\004 \001(" +
      "\0162\014.UserDTO.Sex\022\022\n\ncreateTime\030\005 \001(\003\022\022\n\nm" +
      "odifyTime\030\006 \001(\003\"\033\n\003Sex\022\010\n\004male\020\000\022\n\n\006fema" +
      "le\020\001B\036\n\014com.zh.modelB\014UserDTOModelP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserDTO_descriptor,
        new String[] { "Id", "Code", "NickName", "Sex", "CreateTime", "ModifyTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
