// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zh.model;

/**
 * Protobuf type {@code UserDTO}
 */
public  final class UserDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserDTO)
        UserDTOOrBuilder {
  // Use UserDTO.newBuilder() to construct.
  private UserDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserDTO() {
    id_ = "";
    code_ = "";
    nickName_ = "";
    sex_ = 0;
    createTime_ = 0L;
    modifyTime_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UserDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            nickName_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            sex_ = rawValue;
            break;
          }
          case 40: {

            createTime_ = input.readInt64();
            break;
          }
          case 48: {

            modifyTime_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return UserDTOModel.internal_static_UserDTO_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return UserDTOModel.internal_static_UserDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UserDTO.class, UserDTO.Builder.class);
  }

  /**
   * Protobuf enum {@code UserDTO.Sex}
   */
  public enum Sex
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>male = 0;</code>
     */
    male(0),
    /**
     * <code>female = 1;</code>
     */
    female(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>male = 0;</code>
     */
    public static final int male_VALUE = 0;
    /**
     * <code>female = 1;</code>
     */
    public static final int female_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Sex valueOf(int value) {
      return forNumber(value);
    }

    public static Sex forNumber(int value) {
      switch (value) {
        case 0: return male;
        case 1: return female;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sex>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sex> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
            public Sex findValueByNumber(int number) {
              return Sex.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return UserDTO.getDescriptor().getEnumTypes().get(0);
    }

    private static final Sex[] VALUES = values();

    public static Sex valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sex(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:UserDTO.Sex)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile Object id_;
  /**
   * <code>optional string id = 1;</code>
   */
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>optional string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private volatile Object code_;
  /**
   * <code>optional string code = 2;</code>
   */
  public String getCode() {
    Object ref = code_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>optional string code = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCodeBytes() {
    Object ref = code_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 3;
  private volatile Object nickName_;
  /**
   * <code>optional string nickName = 3;</code>
   */
  public String getNickName() {
    Object ref = nickName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nickName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nickName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNickNameBytes() {
    Object ref = nickName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nickName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEX_FIELD_NUMBER = 4;
  private int sex_;
  /**
   * <code>optional .UserDTO.Sex sex = 4;</code>
   */
  public int getSexValue() {
    return sex_;
  }
  /**
   * <code>optional .UserDTO.Sex sex = 4;</code>
   */
  public UserDTO.Sex getSex() {
    UserDTO.Sex result = UserDTO.Sex.valueOf(sex_);
    return result == null ? UserDTO.Sex.UNRECOGNIZED : result;
  }

  public static final int CREATETIME_FIELD_NUMBER = 5;
  private long createTime_;
  /**
   * <code>optional int64 createTime = 5;</code>
   */
  public long getCreateTime() {
    return createTime_;
  }

  public static final int MODIFYTIME_FIELD_NUMBER = 6;
  private long modifyTime_;
  /**
   * <code>optional int64 modifyTime = 6;</code>
   */
  public long getModifyTime() {
    return modifyTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
    }
    if (!getNickNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickName_);
    }
    if (sex_ != UserDTO.Sex.male.getNumber()) {
      output.writeEnum(4, sex_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(5, createTime_);
    }
    if (modifyTime_ != 0L) {
      output.writeInt64(6, modifyTime_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
    }
    if (!getNickNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickName_);
    }
    if (sex_ != UserDTO.Sex.male.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, sex_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, createTime_);
    }
    if (modifyTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, modifyTime_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UserDTO)) {
      return super.equals(obj);
    }
    UserDTO other = (UserDTO) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getCode()
        .equals(other.getCode());
    result = result && getNickName()
        .equals(other.getNickName());
    result = result && sex_ == other.sex_;
    result = result && (getCreateTime()
        == other.getCreateTime());
    result = result && (getModifyTime()
        == other.getModifyTime());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNickName().hashCode();
    hash = (37 * hash) + SEX_FIELD_NUMBER;
    hash = (53 * hash) + sex_;
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + MODIFYTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getModifyTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UserDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UserDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UserDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UserDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UserDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UserDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UserDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserDTO)
          UserDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserDTOModel.internal_static_UserDTO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserDTOModel.internal_static_UserDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserDTO.class, UserDTO.Builder.class);
    }

    // Construct using com.zh.model.UserDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      code_ = "";

      nickName_ = "";

      sex_ = 0;

      createTime_ = 0L;

      modifyTime_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return UserDTOModel.internal_static_UserDTO_descriptor;
    }

    public UserDTO getDefaultInstanceForType() {
      return UserDTO.getDefaultInstance();
    }

    public UserDTO build() {
      UserDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UserDTO buildPartial() {
      UserDTO result = new UserDTO(this);
      result.id_ = id_;
      result.code_ = code_;
      result.nickName_ = nickName_;
      result.sex_ = sex_;
      result.createTime_ = createTime_;
      result.modifyTime_ = modifyTime_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UserDTO) {
        return mergeFrom((UserDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UserDTO other) {
      if (other == UserDTO.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (!other.getNickName().isEmpty()) {
        nickName_ = other.nickName_;
        onChanged();
      }
      if (other.sex_ != 0) {
        setSexValue(other.getSexValue());
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getModifyTime() != 0L) {
        setModifyTime(other.getModifyTime());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UserDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UserDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object id_ = "";
    /**
     * <code>optional string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder setId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder clearId() {

      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      id_ = value;
      onChanged();
      return this;
    }

    private Object code_ = "";
    /**
     * <code>optional string code = 2;</code>
     */
    public String getCode() {
      Object ref = code_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public Builder setCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public Builder clearCode() {

      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string code = 2;</code>
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      code_ = value;
      onChanged();
      return this;
    }

    private Object nickName_ = "";
    /**
     * <code>optional string nickName = 3;</code>
     */
    public String getNickName() {
      Object ref = nickName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string nickName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nickName = 3;</code>
     */
    public Builder setNickName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      nickName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nickName = 3;</code>
     */
    public Builder clearNickName() {

      nickName_ = getDefaultInstance().getNickName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nickName = 3;</code>
     */
    public Builder setNickNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      nickName_ = value;
      onChanged();
      return this;
    }

    private int sex_ = 0;
    /**
     * <code>optional .UserDTO.Sex sex = 4;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <code>optional .UserDTO.Sex sex = 4;</code>
     */
    public Builder setSexValue(int value) {
      sex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .UserDTO.Sex sex = 4;</code>
     */
    public UserDTO.Sex getSex() {
      UserDTO.Sex result = UserDTO.Sex.valueOf(sex_);
      return result == null ? UserDTO.Sex.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .UserDTO.Sex sex = 4;</code>
     */
    public Builder setSex(UserDTO.Sex value) {
      if (value == null) {
        throw new NullPointerException();
      }

      sex_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .UserDTO.Sex sex = 4;</code>
     */
    public Builder clearSex() {

      sex_ = 0;
      onChanged();
      return this;
    }

    private long createTime_ ;
    /**
     * <code>optional int64 createTime = 5;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }
    /**
     * <code>optional int64 createTime = 5;</code>
     */
    public Builder setCreateTime(long value) {

      createTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 createTime = 5;</code>
     */
    public Builder clearCreateTime() {

      createTime_ = 0L;
      onChanged();
      return this;
    }

    private long modifyTime_ ;
    /**
     * <code>optional int64 modifyTime = 6;</code>
     */
    public long getModifyTime() {
      return modifyTime_;
    }
    /**
     * <code>optional int64 modifyTime = 6;</code>
     */
    public Builder setModifyTime(long value) {

      modifyTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 modifyTime = 6;</code>
     */
    public Builder clearModifyTime() {

      modifyTime_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:UserDTO)
  }

  // @@protoc_insertion_point(class_scope:UserDTO)
  private static final UserDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UserDTO();
  }

  public static UserDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserDTO>
      PARSER = new com.google.protobuf.AbstractParser<UserDTO>() {
    public UserDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserDTO> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UserDTO> getParserForType() {
    return PARSER;
  }

  public UserDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

