// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zh.model;

public interface UserDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string code = 2;</code>
   */
  String getCode();
  /**
   * <code>optional string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string nickName = 3;</code>
   */
  String getNickName();
  /**
   * <code>optional string nickName = 3;</code>
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <code>optional .UserDTO.Sex sex = 4;</code>
   */
  int getSexValue();
  /**
   * <code>optional .UserDTO.Sex sex = 4;</code>
   */
  UserDTO.Sex getSex();

  /**
   * <code>optional int64 createTime = 5;</code>
   */
  long getCreateTime();

  /**
   * <code>optional int64 modifyTime = 6;</code>
   */
  long getModifyTime();
}
